name: Test R2

on:
  workflow_dispatch:

permissions: read-all

jobs:
  dmg:
    name: Test R2
    runs-on: ubuntu-22.04
    steps:
      - name: Build Macos
        run: |
          mkdir -p artifacts
          echo "hello" > artifacts/test.txt

      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: test
          output-file-url: false
          destination-dir: artifacts
