name: Test macOS dmg

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

env:
  APP_NAME: ${{ secrets.APP_NAME }}
  DEVELOPER_ID_APPLICATION_P12_BASE64: ${{ secrets.DEVELOPER_ID_APPLICATION_P12_BASE64 }}
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  PROVISION_MAC_BASE64: ${{ secrets.PROVISION_MAC_BASE64 }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  DEVELOPER_ID_APPLICATION_SIGNING_IDENTITY: ${{ secrets.DEVELOPER_ID_APPLICATION_SIGNING_IDENTITY }}

jobs:
  dmg:
    name: Package Macos Dmg
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GIT_REPO }}
          ref: main
          token: ${{ secrets.GIT_PAT }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.29.2"

      - name: Build Macos
        run: bash packager/macos.sh

      - uses: actions/upload-artifact@v4
        with:
          name: macos-dmg-artifact
          path: ./*.dmg
